# Action definition

name: 'Vowel Frequency Analyzer'
description: 'Custom action to analyze vowels frequency.'

inputs:
  file: 
    description: 'The path to the text file to analyze (e.g., data.txt).'
    required: true

runs: 
  using: 'docker'
  image: https://github.com/georges034302/ppc-tester-docker/pkgs/container/vowel-frequency-analyzer:latest
  entrypoint: "/app/.github/scripts/entrypoint.sh"
  env:
    FILE: '${{ inputs.file }}'